# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: session.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='session.proto',
  package='desk',
  syntax='proto3',
  serialized_pb=_b('\n\rsession.proto\x12\x04\x64\x65sk\"Z\n\x07Session\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x11\n\ttimeStart\x18\x03 \x01(\t\x12\x0f\n\x07timeEnd\x18\x04 \x01(\t\x12\r\n\x05title\x18\x05 \x01(\t\"1\n\x0bSessionList\x12\"\n\x0bsessionList\x18\x01 \x03(\x0b\x32\r.desk.Session\"_\n\rSessionObject\x12\x1e\n\x07session\x18\x01 \x01(\x0b\x32\r.desk.Session\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ninsertTime\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\"s\n\x15SessionObjectMovement\x12*\n\rsessionObject\x18\x01 \x01(\x0b\x32\x13.desk.SessionObject\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x12\n\ninsertTime\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\t\"1\n\x0fSessionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\x08\x42\x15\xaa\x02\x12\x64\x65skx_uwp.protobufb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_SESSION = _descriptor.Descriptor(
  name='Session',
  full_name='desk.Session',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='desk.Session.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='username', full_name='desk.Session.username', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeStart', full_name='desk.Session.timeStart', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='timeEnd', full_name='desk.Session.timeEnd', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='desk.Session.title', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=113,
)


_SESSIONLIST = _descriptor.Descriptor(
  name='SessionList',
  full_name='desk.SessionList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionList', full_name='desk.SessionList.sessionList', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=115,
  serialized_end=164,
)


_SESSIONOBJECT = _descriptor.Descriptor(
  name='SessionObject',
  full_name='desk.SessionObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='session', full_name='desk.SessionObject.session', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='desk.SessionObject.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='insertTime', full_name='desk.SessionObject.insertTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='desk.SessionObject.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=261,
)


_SESSIONOBJECTMOVEMENT = _descriptor.Descriptor(
  name='SessionObjectMovement',
  full_name='desk.SessionObjectMovement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sessionObject', full_name='desk.SessionObjectMovement.sessionObject', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='desk.SessionObjectMovement.type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='insertTime', full_name='desk.SessionObjectMovement.insertTime', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='data', full_name='desk.SessionObjectMovement.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=263,
  serialized_end=378,
)


_SESSIONRESPONSE = _descriptor.Descriptor(
  name='SessionResponse',
  full_name='desk.SessionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='desk.SessionResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='error', full_name='desk.SessionResponse.error', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=380,
  serialized_end=429,
)

_SESSIONLIST.fields_by_name['sessionList'].message_type = _SESSION
_SESSIONOBJECT.fields_by_name['session'].message_type = _SESSION
_SESSIONOBJECTMOVEMENT.fields_by_name['sessionObject'].message_type = _SESSIONOBJECT
DESCRIPTOR.message_types_by_name['Session'] = _SESSION
DESCRIPTOR.message_types_by_name['SessionList'] = _SESSIONLIST
DESCRIPTOR.message_types_by_name['SessionObject'] = _SESSIONOBJECT
DESCRIPTOR.message_types_by_name['SessionObjectMovement'] = _SESSIONOBJECTMOVEMENT
DESCRIPTOR.message_types_by_name['SessionResponse'] = _SESSIONRESPONSE

Session = _reflection.GeneratedProtocolMessageType('Session', (_message.Message,), dict(
  DESCRIPTOR = _SESSION,
  __module__ = 'session_pb2'
  # @@protoc_insertion_point(class_scope:desk.Session)
  ))
_sym_db.RegisterMessage(Session)

SessionList = _reflection.GeneratedProtocolMessageType('SessionList', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONLIST,
  __module__ = 'session_pb2'
  # @@protoc_insertion_point(class_scope:desk.SessionList)
  ))
_sym_db.RegisterMessage(SessionList)

SessionObject = _reflection.GeneratedProtocolMessageType('SessionObject', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONOBJECT,
  __module__ = 'session_pb2'
  # @@protoc_insertion_point(class_scope:desk.SessionObject)
  ))
_sym_db.RegisterMessage(SessionObject)

SessionObjectMovement = _reflection.GeneratedProtocolMessageType('SessionObjectMovement', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONOBJECTMOVEMENT,
  __module__ = 'session_pb2'
  # @@protoc_insertion_point(class_scope:desk.SessionObjectMovement)
  ))
_sym_db.RegisterMessage(SessionObjectMovement)

SessionResponse = _reflection.GeneratedProtocolMessageType('SessionResponse', (_message.Message,), dict(
  DESCRIPTOR = _SESSIONRESPONSE,
  __module__ = 'session_pb2'
  # @@protoc_insertion_point(class_scope:desk.SessionResponse)
  ))
_sym_db.RegisterMessage(SessionResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\022deskx_uwp.protobuf'))
# @@protoc_insertion_point(module_scope)
