# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0002_auto_20160530_0254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_object',
            name='author',
        ),
    ]
