# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-29 17:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desk', '0004_session_object_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_object',
            name='author',
        ),
    ]
